### PR TITLE
add simonb.com

### PR DESCRIPTION
**Pull request by bnomis**
Thanks. Hope this is OK.

### CODE REVIEW

**Comment by alexott** [comment]
I'm sorry, but I don't see any clojure-related posts...

**Comment by bnomis** [comment]
I'm about to start writing about Clojure[Script], Om Next, DataScript etc. Starting with this project I've been working on https://github.com/bnomis/om-next-datascript-localisation-demo

Thanks

**Comment by alexott** [comment]
Ok, thanks for clarification!

**Comment by bnomis** [comment]
Thank you.

**Pull request merged**
