### PR TITLE
Add Applied Science' blog feed URL

### PR DESCRIPTION
**Pull request by daveliepmann**
Hi, thanks for maintaining this project. This PR adds our studio's blog feed.

### CODE REVIEW

**Comment by alexott** [comment]
Thank you! I've manually merged it into twitter-integration branch, and added the Twitter handle

**Comment by daveliepmann** [comment]
Thanks, Alex! Could I ask why the two branches are separate?

**Comment by alexott** [comment]
It's mostly coordination - adding the Twitter support required the more recent version of Python, and existing instance of Planet is quite old, so we created new one, but it's not completely migrated, so they are running in parallel. I hope that switch will happen soon...

**Comment by daveliepmann** [comment]
I see the article on the twitter account. (Thanks!) Is there anything I can do to get our feed added to the planet.clojure.in website and RSS feed as well?

**Comment by alexott** [comment]
I need to look how to pickup only changes in the config.ini, apply to master. I unfortunately can't merge everything as it will break the current planet...

**Comment by daveliepmann** [comment]
@alexott Is there anything I can do to get this on the RSS feed and website? It appears to me that reopening and merging to `master` would work, but if there's anything else we can do from our end just let us know.

**Comment by alexott** [comment]
Sorry for delay- I'll look and merge tomorrow

**Comment by alexott** [comment]
But it's really should be already be in both branches

**Comment by alexott** [comment]
Hello Dave

I've checked - your blog presents in both branches. But it's not published on the "main" site unfortunately, only on the Twitter. I suspect that there is a problem with SSL or something like because of the old Python versions.

I still didn't get an answer about switching to newer version of the site :-(

**Comment by daveliepmann** [comment]
OK, thanks for investigating Alex :)

**Comment by alexott** [comment]
@daveliepmann Now it should use the new instance, with newer Python version, etc.

**Pull request closed without merging**
