### PR TITLE
Add page programadorwebvalencia

### PR DESCRIPTION
**Pull request by tanrax**

### CODE REVIEW

**Comment by alexott** [comment]
Hi Andros

I see right now only posts in Spanish - do you plan to write in English? I need to think, maybe we can make a separate, per language, feed...

**Comment by tanrax** [comment]
@alexott As I had seen content in other languages and thought it didn't matter the language... What if I add a label with the language of the article?

**Comment by alexott** [comment]
That's really an error that I always forget to fix. But let me organize the poll, and ask if people would be interested to see content not only in English

**Comment by tanrax** [comment]
> That's really an error that I always forget to fix. But let me organize the poll, and ask if people would be interested to see content not only in English

No problem :)
And create parallel websites for each language?

**Comment by alexott** [comment]
I need to discuss how to better make it. For Planet Emacsen we had parallel versions, mapped into different directories, IIRC

**Pull request closed without merging**
